
export const metadata = {
  title: 'Home : Work Manager',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <div>
        <h1 className="text-5xl">welcome to work manager</h1>
    </div>
   
  )
}
